package com.porsche.aaos.platform.telemetry.collector.system

import android.app.ActivityManager
import android.app.usage.NetworkStatsManager
import android.content.Context
import android.net.ConnectivityManager
import com.porsche.aaos.platform.telemetry.collector.Collector
import com.porsche.aaos.platform.telemetry.core.logging.Logger
import com.porsche.aaos.platform.telemetry.telemetry.Telemetry
import com.porsche.aaos.platform.telemetry.telemetry.TelemetryEvent
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import javax.inject.Inject
import kotlin.coroutines.coroutineContext
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive

/**
 * Self-monitoring collector: tracks resource usage of our own DataCollector process.
 *
 * Emits SelfMonitor_Usage heartbeat events with:
 * - Process CPU time (user + system jiffies from /proc/self/stat)
 * - Process RSS memory (from /proc/self/statm)
 * - Network traffic generated by our own UID (via NetworkStatsManager)
 * - Thread count
 *
 * This allows analysis of the telemetry service's own footprint on the system.
 */
class SelfMonitorCollector @Inject constructor(
    @ApplicationContext private val context: Context,
    private val telemetry: Telemetry,
    private val logger: Logger,
) : Collector {

    override val name: String = "SelfMonitor"
    private val signalId = TelemetryEvent.signalId("${name}Collector")

    @Volatile
    private var running = false

    private val samples = mutableListOf<List<Any>>()

    // Previous jiffies for delta CPU calculation
    private var prevUserJiffies = 0L
    private var prevSystemJiffies = 0L
    private var prevTimestamp = 0L

    // Our own UID for network queries
    private val myUid: Int by lazy { android.os.Process.myUid() }

    override suspend fun start() {
        running = true
        logger.i(TAG, "Starting self-monitoring (own PID=${android.os.Process.myPid()}, UID=$myUid)")

        delay(STAGGER_DELAY_MS)

        // Seed initial CPU readings
        readProcessCpuJiffies()?.let { (user, system) ->
            prevUserJiffies = user
            prevSystemJiffies = system
            prevTimestamp = System.currentTimeMillis()
        }

        while (running && coroutineContext.isActive) {
            delay(SAMPLE_INTERVAL_MS)
            collectSample()

            if (samples.size >= SAMPLES_PER_BATCH) {
                flush()
            }
        }
    }

    override fun stop() {
        running = false
        logger.i(TAG, "Stopped")
    }

    @Suppress("TooGenericExceptionCaught")
    private fun collectSample() {
        try {
            val now = System.currentTimeMillis()

            // Process CPU — delta jiffies since last sample
            val cpuPct = readProcessCpuJiffies()?.let { (user, system) ->
                val userDelta = user - prevUserJiffies
                val systemDelta = system - prevSystemJiffies
                val timeDeltaMs = now - prevTimestamp
                prevUserJiffies = user
                prevSystemJiffies = system
                prevTimestamp = now

                if (timeDeltaMs > 0) {
                    // jiffies are in 1/100s (10ms). Convert to percentage.
                    val totalJiffies = userDelta + systemDelta
                    val elapsedJiffies = timeDeltaMs / JIFFY_MS
                    if (elapsedJiffies > 0) {
                        (totalJiffies.toDouble() / elapsedJiffies * 100).coerceIn(0.0, 100.0)
                    } else {
                        0.0
                    }
                } else {
                    0.0
                }
            } ?: 0.0

            // Process memory — RSS from /proc/self/statm (pages)
            val rssKb = readProcessRssKb()

            // Process memory — from ActivityManager (more accurate for Android)
            val amMemMb = readActivityManagerMemory()

            // Thread count
            val threadCount = Thread.activeCount()

            // Network — own UID traffic
            val netTraffic = readOwnNetworkTraffic()

            synchronized(samples) {
                samples.add(
                    listOf(
                        now,
                        "%.1f".format(cpuPct).toDouble(),
                        rssKb,
                        amMemMb,
                        threadCount,
                        netTraffic.first,  // rxBytes
                        netTraffic.second, // txBytes
                    ),
                )
            }
        } catch (e: Exception) {
            logger.e(TAG, "Failed to collect self-monitor sample: ${e.message}")
        }
    }

    private fun flush() {
        synchronized(samples) {
            if (samples.isEmpty()) return
            telemetry.send(
                TelemetryEvent(
                    signalId = signalId,
                    payload = mapOf(
                        "actionName" to "SelfMonitor_Usage",
                        "trigger" to "heartbeat",
                        "metadata" to mapOf(
                            "pid" to android.os.Process.myPid(),
                            "uid" to myUid,
                            "sampleSchema" to listOf(
                                "timestampMillis",
                                "cpuPct",
                                "rssKb",
                                "memMb",
                                "threadCount",
                                "rxBytes",
                                "txBytes",
                            ),
                            "samples" to samples.toList(),
                        ),
                    ),
                ),
            )
            samples.clear()
        }
    }

    /**
     * Reads user and system CPU jiffies from /proc/self/stat.
     * Field 14 = utime (user), field 15 = stime (system).
     */
    @Suppress("TooGenericExceptionCaught", "MagicNumber")
    private fun readProcessCpuJiffies(): Pair<Long, Long>? {
        return try {
            val stat = File("/proc/self/stat").readText()
            // Fields after the command name (in parens) — find closing paren
            val afterCmd = stat.substringAfterLast(") ")
            val fields = afterCmd.split(" ")
            // fields[0] = state, fields[1..] = ppid, pgrp, ... utime=11, stime=12 (0-indexed after state)
            val utime = fields.getOrNull(UTIME_INDEX)?.toLongOrNull() ?: return null
            val stime = fields.getOrNull(STIME_INDEX)?.toLongOrNull() ?: return null
            Pair(utime, stime)
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Reads RSS from /proc/self/statm (second field, in pages).
     */
    @Suppress("TooGenericExceptionCaught")
    private fun readProcessRssKb(): Long {
        return try {
            val fields = File("/proc/self/statm").readText().trim().split(" ")
            val rssPages = fields.getOrNull(1)?.toLongOrNull() ?: 0L
            rssPages * PAGE_SIZE_KB
        } catch (e: Exception) {
            0L
        }
    }

    /**
     * Uses ActivityManager to get our process memory (PSS).
     */
    @Suppress("TooGenericExceptionCaught")
    private fun readActivityManagerMemory(): Long {
        return try {
            val am = context.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
            val pid = android.os.Process.myPid()
            val memInfo = am.getProcessMemoryInfo(intArrayOf(pid))
            if (memInfo.isNotEmpty()) {
                memInfo[0].totalPss.toLong() / KB_PER_MB
            } else {
                0L
            }
        } catch (e: Exception) {
            0L
        }
    }

    /**
     * Reads own UID network traffic from TrafficStats.
     * This works for user-0 UIDs; for cross-user it falls back to 0.
     */
    private fun readOwnNetworkTraffic(): Pair<Long, Long> {
        val rx = android.net.TrafficStats.getUidRxBytes(myUid)
        val tx = android.net.TrafficStats.getUidTxBytes(myUid)
        return Pair(
            if (rx == android.net.TrafficStats.UNSUPPORTED.toLong()) 0L else rx,
            if (tx == android.net.TrafficStats.UNSUPPORTED.toLong()) 0L else tx,
        )
    }

    companion object {
        private const val TAG = "SelfMonitorCollector"
        private const val SAMPLE_INTERVAL_MS = 5_000L
        private const val SAMPLES_PER_BATCH = 12
        private const val STAGGER_DELAY_MS = 8_000L
        private const val JIFFY_MS = 10L // 1 jiffy = 10ms on most Linux/Android
        private const val PAGE_SIZE_KB = 4L // Standard 4KB pages
        private const val KB_PER_MB = 1024L
        private const val UTIME_INDEX = 11
        private const val STIME_INDEX = 12
    }
}
